// client/src/api/seedConversations.js
// 50 lightweight sample conversation pairs mixing greetings, names, and math.
export const conversationSeeds = [
  { prompt: 'hi', reply: 'hlo' },
  { prompt: 'hello', reply: 'hlo' },
  { prompt: 'hey', reply: 'hlo' },
  { prompt: 'hi there', reply: 'hlo' },
  { prompt: 'howdy', reply: 'hlo' },
  { prompt: 'yo', reply: 'hlo' },
  { prompt: 'namaste', reply: 'hlo' },
  { prompt: 'hola', reply: 'hlo' },
  { prompt: 'sup', reply: 'hlo' },
  { prompt: 'hai', reply: 'hlo' },

  { prompt: 'my name is alice', reply: 'Nice to meet you, Alice!' },
  { prompt: 'my name is bob', reply: 'Nice to meet you, Bob!' },
  { prompt: 'my name is charlie', reply: 'Nice to meet you, Charlie!' },
  { prompt: 'i am dave', reply: 'Nice to meet you, Dave!' },
  { prompt: 'i am eva', reply: 'Nice to meet you, Eva!' },
  { prompt: 'call me frank', reply: 'Nice to meet you, Frank!' },
  { prompt: 'call me grace', reply: 'Nice to meet you, Grace!' },
  { prompt: 'i am harry', reply: 'Nice to meet you, Harry!' },
  { prompt: 'i am isabel', reply: 'Nice to meet you, Isabel!' },
  { prompt: 'my name is jack', reply: 'Nice to meet you, Jack!' },

  { prompt: '2+2', reply: '4' },
  { prompt: '3+5', reply: '8' },
  { prompt: '10-3', reply: '7' },
  { prompt: '6*7', reply: '42' },
  { prompt: '6x7', reply: '42' },
  { prompt: '42/6', reply: '7' },
  { prompt: '100/4', reply: '25' },
  { prompt: '9+1', reply: '10' },
  { prompt: '15-5', reply: '10' },
  { prompt: '3*3', reply: '9' },

  { prompt: 'what is 2+3', reply: '5' },
  { prompt: 'what is 10-4', reply: '6' },
  { prompt: 'what is 8/2', reply: '4' },
  { prompt: 'what is 5*5', reply: '25' },
  { prompt: 'what is 12+13', reply: '25' },
  { prompt: 'what is 9-2', reply: '7' },
  { prompt: 'what is 7*8', reply: '56' },
  { prompt: 'what is 16/4', reply: '4' },
  { prompt: 'what is 20+1', reply: '21' },
  { prompt: 'what is 14-9', reply: '5' },

  { prompt: 'hi my name is anu', reply: 'Nice to meet you, Anu!' },
  { prompt: 'hello my name is vikram', reply: 'Nice to meet you, Vikram!' },
  { prompt: 'i am adi', reply: 'Nice to meet you, Adi!' },
  { prompt: 'call me kiran', reply: 'Nice to meet you, Kiran!' },
  { prompt: 'hey i am sam', reply: 'Nice to meet you, Sam!' },
  { prompt: 'hi adi', reply: 'hlo' },
  { prompt: 'hello friend', reply: 'hlo' },
  { prompt: 'hey there', reply: 'hlo' },
  { prompt: 'greetings', reply: 'hlo' },
  { prompt: 'good day', reply: 'hlo' }
];